(scripts, hyprland): refactor scripts

diff --git a/.local/bin/audiocontrol b/.local/bin/audiocontrol
--- a/.local/bin/audiocontrol
+++ b/.local/bin/audiocontrol
@@ -4,10 +4,8 @@ source "$XDG_BIN_HOME"/pactl_helpers.sh
 
 DEVICE=""
 TOGGLE=false
-INCREMENT=false
-INCREMENT_VALUE=""
-DECREMENT=false
-DECREMENT_VALUE=""
+INCREMENT_VALUE=0
+DECREMENT_VALUE=0
 NOTIFY=false
 
 get_icon_prefix() {
@@ -59,22 +57,23 @@ notify() {
 }
 
 display_help() {
-	printf "Usage: %s [DEVICE] [OPTION]...\n" "$0"
+	printf "Usage: audiocontrol DEVICE [OPTIONS]\n"
 	printf "Control audio input and output devices.\n\n"
 	printf "Options:\n"
-	printf "  -i, --input [OPTION]...    Control audio input device\n"
-	printf "  -o, --output [OPTION]...   Control audio output device\n"
-	printf "  -h, --help                 Display this help and exit\n\n"
+	printf "  -i, --input [OPTIONS]     Control audio input device\n"
+	printf "  -o, --output [OPTIONS]    Control audio output device\n"
+	printf "  -h, --help                  Display this help and exit\n\n"
 	printf "Device options:\n"
-	printf "  -t, --toggle               Toggle mute\n"
-	printf "  -i, --increment [VALUE]    Increment volume by VALUE\n"
-	printf "  -d, --decrement [VALUE]    Decrement volume by VALUE\n"
-	printf "  -n, --notify               Display volume notification\n\n"
+	printf "  -t, --toggle                Toggle mute\n"
+	printf "  -i, --increment VALUE       Increment volume by VALUE\n"
+	printf "  -d, --decrement VALUE       Decrement volume by VALUE\n"
+	printf "  --notify                    Display volume notification\n\n"
 }
 
 device_help() {
 	local flag=""
 	local device=""
+
 	if [[ $DEVICE == "sink" ]]; then
 		flag="-o, --output"
 		device="output"
@@ -83,17 +82,28 @@ device_help() {
 		device="input"
 	fi
 
-	printf "Usage: %s %s [OPTION]...\n" "$0" "$flag"
+	printf "Usage: audiocontrol %s [OPTIONS]\n" "$flag"
 	printf "Control %s audio device\n\n" "$device"
 	printf "Options:\n"
-	printf "  -t, --toggle               Toggle mute\n"
-	printf "  -i, --increment [VALUE]    Increment volume by VALUE\n"
-	printf "  -d, --decrement [VALUE]    Decrement volume by VALUE\n"
-	printf "  -n, --notify               Display volume notification\n\n"
+	printf "  -t, --toggle             Toggle mute\n"
+	printf "  -i, --increment VALUE    Increment volume by VALUE\n"
+	printf "  -d, --decrement VALUE    Decrement volume by VALUE\n"
+	printf "  --notify                 Display volume notification\n\n"
+	printf "  -h, --help               Display this help and exit\n\n"
 }
 
+if [ "$#" -eq 0 ]; then
+	display_help
+	exit 1
+fi
+
 handle_device() {
-	local -r options=$(getopt -o ti:d:nh --long toggle,increment:,decrement:,notify,help -- "$@")
+	if [ "$#" -eq 0 ]; then
+		device_help
+		exit 1
+	fi
+
+	local -r options=$(getopt -o ti:d:nh --long toggle,increment:,decrement:,notify,help -n "audiocontrol" -- "$@")
 	eval set -- "$options"
 	while true; do
 		case "$1" in
@@ -102,16 +112,22 @@ handle_device() {
 			shift
 			;;
 		-i | --increment)
-			INCREMENT=true
+			if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+				printf "Error: Invalid volume increment value.\n" >&2
+				exit 1
+			fi
 			INCREMENT_VALUE="$2"
 			shift 2
 			;;
 		-d | --decrement)
-			DECREMENT=true
+			if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+				printf "Error: Invalid volume increment value.\n" >&2
+				exit 1
+			fi
 			DECREMENT_VALUE="$2"
 			shift 2
 			;;
-		-n | --notify)
+		--notify)
 			NOTIFY=true
 			shift
 			;;
@@ -123,15 +139,10 @@ handle_device() {
 			shift
 			break
 			;;
-		*)
-			echo "Invalid option: $1" >&2
-			exit 1
-			;;
 		esac
 	done
 }
 
-options=$(getopt -o ioh --long input,output,help -- "$1")
 while true; do
 	case "$1" in
 	-i | --input)
@@ -157,15 +168,16 @@ while true; do
 	esac
 done
 
+if [[ -z $DEVICE ]]; then
+	printf "Error: No device specified.\n" >&2
+	exit 1
+fi
+
 if $TOGGLE; then
 	toggle
-fi
-
-if $INCREMENT; then
+elif ((INCREMENT_VALUE > 0)); then
 	increment
-fi
-
-if $DECREMENT; then
+elif ((DECREMENT_VALUE > 0)); then
 	decrement
 fi
 
diff --git a/.local/bin/brightness b/.local/bin/brightness
--- a/.local/bin/brightness
+++ b/.local/bin/brightness
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-get_brightness() {
-	brightnessctl -m | tr ',' ' ' | awk '{print $4}' | sed 's/%//'
-}
+INCREMENT_VALUE=0
+DECREMENT_VALUE=0
+NOTIFY=false
 
 get_icon() {
 	output_volume="$(get_brightness)"
@@ -18,21 +18,92 @@ get_icon() {
 	fi
 }
 
-increase_brightness() {
-	brightnessctl s +5%
-	notify
+get_brightness() {
+	brightnessctl -m | tr ',' ' ' | awk '{print $4}' | sed 's/%//'
 }
 
-decrease_brightness() {
-	brightnessctl s 5%-
-	notify
+set_brightness() {
+	local n="$1"
+	local sign="$2"
+	local -r curr=$(get_brightness)
+	local -r new_brightness=$(echo "$curr $sign $n" | bc)
+	brightnessctl -q s "$new_brightness"%
+}
+
+increment() {
+	set_brightness "$INCREMENT_VALUE" +
+}
+
+decrement() {
+	set_brightness "$DECREMENT_VALUE" -
 }
 
 notify() {
-	notify-send -a "Brightness" "$(get_brightness)%" -i "$(get_icon)" -u low -t 2000 -h int:value:"$(get_brightness)" -r 999
+	local -r icon=$(get_icon)
+	local -r brightness=$(get_brightness)
+	notify-send -a "Brightness" "$brightness%" -i "$icon" -u low -t 2000 -h int:value:"$brightness" -r 999
 }
 
-case "$1" in
-"increase") increase_brightness ;;
-"decrease") decrease_brightness ;;
-esac
+display_help() {
+	printf "Usage: brightness [OPTIONS]\n"
+	printf "Control screen brightness.\n\n"
+	printf "Options:\n"
+	printf "  -i, --increment VALUE    Increase the brightness by VALUE percent\n"
+	printf "  -d, --decrement VALUE    Decrease the brightness by VALUE percent\n"
+	printf "      --notify             Display brightness notification\n"
+	printf "  -h, --help               Display this help and exit\n\n"
+}
+
+if [ "$#" -eq 0 ]; then
+	display_help
+	exit 1
+fi
+
+options=$(getopt -o i:d:h --long increment:,decrement:,notify,help -n "brightness" -- "$@")
+eval set -- "$options"
+while true; do
+	case "$1" in
+	-i | --increment)
+		if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+			printf "Error: Invalid volume increment value.\n" >&2
+			exit 1
+		fi
+		INCREMENT_VALUE="$2"
+		shift 2
+		;;
+	-d | --decrement)
+		if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+			printf "Error: Invalid volume increment value.\n" >&2
+			exit 1
+		fi
+		DECREMENT_VALUE="$2"
+		shift 2
+		;;
+	--notify)
+		NOTIFY=true
+		shift
+		;;
+	-h | --help)
+		display_help
+		exit 0
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		echo "Invalid option: $1"
+		exit 1
+		;;
+	esac
+done
+
+if ((INCREMENT_VALUE > 0)); then
+	increment
+elif ((DECREMENT_VALUE > 0)); then
+	decrement
+fi
+
+if $NOTIFY; then
+	notify
+fi
diff --git a/.local/bin/mpris b/.local/bin/mpris
--- a/.local/bin/mpris
+++ b/.local/bin/mpris
@@ -1,17 +1,27 @@
 #!/bin/bash
 
+VOLUME_INCREMENT_VALUE=0
+VOLUME_DECREMENT_VALUE=0
+
+TRACK_NEXT=false
+TRACK_PREV=false
+
+PLAYER_TOGGLE=false
+PLAYER_NEXT=false
+PLAYER_PREV=false
+
+NOTIFY_VOLUME=false
+NOTIFY_TRACK=false
+
 cache_art() {
 	local artUrl=$1
 	if [ -z "$artUrl" ]; then
 		printf ""
 	fi
 
-	local cache_dir
-	cache_dir="$HOME/.cache/mpris"
-	local art_name
-	art_name=$(basename "$artUrl")
-	local art_path
-	art_path="$cache_dir/$art_name"
+	local cache_dir="$HOME/.cache/mpris"
+	local -r art_name=$(basename "$artUrl")
+	local -r art_path="$cache_dir/$art_name"
 
 	if [ ! -d "$cache_dir" ]; then
 		mkdir -p "$cache_dir"
@@ -25,14 +35,10 @@ cache_art() {
 }
 
 get_metadata() {
-	local artist
-	artist=$(playerctl metadata xesam:artist)
-	local album
-	album=$(playerctl metadata xesam:album)
-	local title
-	title=$(playerctl metadata xesam:title)
-	local art_path
-	art_path=" "
+	local -r artist=$(playerctl metadata xesam:artist)
+	local -r album=$(playerctl metadata xesam:album)
+	local -r title=$(playerctl metadata xesam:title)
+	local art_path=" "
 	if grep -q "mpris:artUrl" <<<"$(playerctl metadata)"; then
 		art_path=$(cache_art "$(playerctl metadata mpris:artUrl)")
 	fi
@@ -43,35 +49,26 @@ get_volume() {
 	playerctl volume | awk '{print int($1 * 100)}'
 }
 
-volume_change() {
-	local sign
-	sign="$1"
-	local n
-	n=${2:-5}
-	local curr
-	curr=$(get_volume)
+set_volume() {
+	local n="$1"
+	local sign="$2"
+	local -r curr=$(get_volume)
 	playerctl volume "$(echo "scale=2;($curr $sign $n)/100" | bc)"
 }
 
 volume_increment() {
-	volume_change "+" "$1"
+	set_volume "$VOLUME_INCREMENT_VALUE" +
 }
 
 volume_decrement() {
-	volume_change "-" "$1"
+	set_volume "$VOLUME_DECREMENT_VALUE" -
 }
 
 volume_notify() {
 	local metadata
 	IFS=":" read -ra metadata <<<"$(get_metadata)"
-	local volume
-	volume=$(get_volume)
+	local -r volume=$(get_volume)
 	dunstify "${metadata[2]}" "${metadata[0]} ${metadata[1]:+- ${metadata[1]}}\n<b>Volume ${volume}%</b>" -i "${metadata[3]}" -u low -t 2000 -h int:value:"${volume}" -r 998
-}
-
-volume_help() {
-	printf "Usage: mpris volume [increment|decrement|notify] [value]\n"
-	exit 1
 }
 
 track_next() {
@@ -88,11 +85,6 @@ track_notify() {
 	dunstify "${metadata[2]}" "${metadata[0]} ${metadata[1]:+- ${metadata[1]}}" -i "${metadata[3]}" -u low -t 2000 -r 998
 }
 
-track_help() {
-	printf "Usage: mpris track [next|prev|notify]\n"
-	exit 1
-}
-
 player_toggle() {
 	playerctl play-pause
 }
@@ -105,43 +97,104 @@ player_prev() {
 	playerctld unshift
 }
 
-player_help() {
-	printf "Usage: mpris player [toggle|next|prev]\n"
-	exit 1
+display_help() {
+	printf "Usage: mpris [OPTIONS]\n"
+	printf "Control MPRIS compatible media players.\n\n"
+	printf "Options:\n"
+	printf "  -i, --volume-increment VALUE    Increment volume by VALUE.\n"
+	printf "  -d, --volume-decrement VALUE    Decrement volume by VALUE.\n"
+	printf "  -n, --track-next                Play the next track.\n"
+	printf "  -p, --track-prev                Play the previous track.\n"
+	printf "  -N, --player-next               Play the next playlist item.\n"
+	printf "  -P, --player-prev               Play the previous playlist item.\n"
+	printf "  -T, --player-toggle             Toggle play/pause.\n"
+	printf "      --notify-volume             Display a notification with the current volume.\n"
+	printf "      --notify-track              Display a notification with the current track.\n"
+	printf "  -h, --help                      Display this help and exit.\n\n"
 }
 
-help() {
-	printf "Usage: mpris [command] [args]\n"
-	printf "Commands:\n"
-	printf "volume [increment|decrement|notify] [value]\n"
-	printf "player [toggle|next|prev]\n"
-	printf "track [next|prev|notify]\n"
+if [ "$#" -eq 0 ]; then
+	display_help
 	exit 1
-}
-
-if (($# == 0)); then
-	help
 fi
 
-IFS=' ' read -ra args <<<"$@"
-case "${args[0]}" in
-"volume") case "${args[1]}" in
-	"increment") volume_increment "${args[2]}" ;;
-	"decrement") volume_decrement "${args[2]}" ;;
-	"notify") volume_notify ;;
-	*) volume_help ;;
-	esac ;;
-"player") case "${args[1]}" in
-	"toggle") player_toggle ;;
-	"next") player_next ;;
-	"prev") player_prev ;;
-	*) player_help ;;
-	esac ;;
-"track") case "${args[1]}" in
-	"next") track_next ;;
-	"prev") track_prev ;;
-	"notify") track_notify ;;
-	*) track_help ;;
-	esac ;;
-*) help ;;
-esac
+options=$(getopt -o i:d:npPNTh --long volume-increment:,volume-decrement:,track-next,track-prev,player-toggle,player-next,player-prev,notify-volume,notify-track,help -n "mpirs" -- "$@")
+eval set -- "$options"
+while true; do
+	case "$1" in
+	-i | --volume-increment)
+		if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+			printf "Error: Invalid volume increment value.\n" >&2
+			exit 1
+		fi
+		VOLUME_INCREMENT_VALUE="$2"
+		shift 2
+		;;
+	-d | --volume-decrement)
+		if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+			printf "Error: Invalid volume decrement value.\n" >&2
+			exit 1
+		fi
+		VOLUME_DECREMENT_VALUE="$2"
+		shift 2
+		;;
+	-n | --track-next)
+		TRACK_NEXT=true
+		shift
+		;;
+	-p | --track-prev)
+		TRACK_PREV=true
+		shift
+		;;
+	-T | --player-toggle)
+		PLAYER_TOGGLE=true
+		shift
+		;;
+	-N | --player-next)
+		PLAYER_NEXT=true
+		shift
+		;;
+	-P | --player-prev)
+		PLAYER_PREV=true
+		shift
+		;;
+	--notify-volume)
+		NOTIFY_VOLUME=true
+		shift
+		;;
+	--notify-track)
+		NOTIFY_TRACK=true
+		shift
+		;;
+	-h | --help)
+		display_help
+		exit 0
+		;;
+	--)
+		shift
+		break
+		;;
+	esac
+done
+
+if ((VOLUME_INCREMENT_VALUE > 0)); then
+	volume_increment
+elif ((VOLUME_DECREMENT_VALUE > 0)); then
+	volume_decrement
+elif $TRACK_NEXT; then
+	track_next
+elif $TRACK_PREV; then
+	track_prev
+elif $PLAYER_TOGGLE; then
+	player_toggle
+elif $PLAYER_NEXT; then
+	player_next
+elif $PLAYER_PREV; then
+	player_prev
+fi
+
+if $NOTIFY_VOLUME; then
+	volume_notify
+elif $NOTIFY_TRACK; then
+	track_notify
+fi
